### ISSUE TITLE
Sample Code for Simple Use Case?

### ISSUE THREAD

**Issue by nickmitchko** [EleutherAI/concept-erasure#1]
Hi, would it be possible to provide a very simply sample to patch a llama model removing a specific singular text concept from the model? The sample provided on the README is slightly confusing

**Comment by norabelrose** [comment]
So far we haven't done concept scrubbing experiments beyond the part-of-speech ones from the paper, so we'd be excited to see you or others try this out!

**Comment by nickmitchko** [comment]
Got it, I'll take a look and see if it's possible

**Comment by norabelrose** [comment]
Yeah I think the trickiest part might be getting it to work for concepts with sparse labels and/or weak supervision, where you don't have a label for each token. Something like [this](https://arxiv.org/abs/2302.02997) might help
